### ISSUE TITLE
Request: upwrap-or use consistent default URLs for circuit commands

### ISSUE THREAD

**Issue by txross** [Cargill/splinter#449]
https://github.com/Cargill/splinter/blob/66cec163ba8f8fcff667741a5e9b1ea66573c95f/cli/src/action/circuit/mod.rs#L157

Some actions, like `circuit create` will default to the typical bind url, http://127.0.0.1:8085, while others like the one referenced above default to the url http://127.0.0.1:8080.

**Comment by shannynalayna** [comment]
This issue has been addressed as of PR #509.
